[package]
name = "rustshit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rustshit"
path = "main.rs"

[dependencies]
anyhow = "1.0"
memchr = "2.7.1"
hex = "0.4.3"